[supervisord]
user=root
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

[program:java_bot]
command=/bin/bash -c "PORT=${PORT:-8085}; java -Xmx400m -Dserver.port=$PORT -Dserver.address=0.0.0.0 -jar /app/build/libs/LeykaBot-1.0-SNAPSHOT.jar"
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=10

[program:humo_listener]
command=/bin/bash -c "python3 /app/payment_listener.py"
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=20
