server:
  port: ${PORT:8085}
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:h2:file:./data/botdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password: ''
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  config:
    import:
      - classpath:config.yml
      - classpath:localization.yml
      - optional:classpath:git.properties