telegram:
  channel-check-subscribe: '@your-bot'
  channel-check-subscribe-url: 'https://t.me/your-bot'
  log-channel-id: -1337
  log-channel-topic-id: 2
  bot:
    token: '8842520350:AAEUc7rb9S42abHVqyM0WU8sGRupEJkxmSU'
    name: 'leykabot'

dev-mode:
  enable: false
  whitelist:
    - 5305539499
    - 8159265215

fragment:
  api-url: 'https://fragment-api.uz/api/v1'
  api-key: '004430c4af6c0b9f42ef24f6540a8eee6c8b1ccf'